DROP TABLE IF EXISTS `updates`;
CREATE TABLE IF NOT EXISTS `updates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(35) NOT NULL,
  `description` varchar(1024) NOT NULL,
  `dateUodated` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `events`;
CREATE TABLE IF NOT EXISTS `events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(35) NOT NULL,
  `description` varchar(1024) NOT NULL,
  `creator` varchar(25) NOT NULL,
  `dateHappening` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `elever`;
CREATE TABLE IF NOT EXISTS `elever` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(1024) NOT NULL,
  `lastname` varchar(1024) NOT NULL,
  `number` int(11) NOT NULL,
  `country` varchar(35) NOT NULL,
  `linje` varchar(35) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=225 DEFAULT CHARSET=latin1;

--
-- Data dump for tabellen `elever`
--

INSERT INTO `elever` (`id`, `firstname`, `lastname`, `number`, `country`, `linje`) VALUES
(1, 'Anders Hinding', 'Bruun-Petersen', 15, 'Spanien', 'Spring\r'),
(2, 'Camilla Lind', 'Wiedicke', 311, 'Indonesien', 'Dans\r'),
(3, 'Ditte Wieland', 'Steffensen', 300, 'Chile', 'Musik\r'),
(4, 'Emma Cordelia Kirstein Harboe', 'Tranberg', 308, 'Ungarn', 'Musik\r'),
(5, 'Johan Redder', 'Mussmann', 77, 'Thailand', 'Spring\r'),
(6, 'Kristian Nørgård', 'Larsen', 61, 'Holland ', 'Fodbold\r'),
(7, 'Kristoffer Frahm', 'Desmareth', 21, 'Belgien ', 'Svømning\r'),
(8, 'Line Bremer', 'Mortensen', 273, 'Sverige ', 'Dans\r'),
(9, 'Louise', 'Maegaard', 267, 'Norge ', 'Spring\r'),
(10, 'Mai Heilmann', 'Reches', 296, 'Malaysia ', 'Dans\r'),
(11, 'Marie Kæseler', 'Nielsen', 279, 'Egypten ', 'Svømning\r'),
(12, 'Mathias', 'Damgaard', 17, 'Brasilien ', 'Spring\r'),
(13, 'Mathias Sillerslev', 'Haurum', 35, 'Japan ', 'Spring\r'),
(14, 'Mette Hinding', 'Bruun-Petersen', 208, 'Indien ', 'Svømning\r'),
(15, 'Michel', 'Lukondji', 68, 'Kina ', 'Spring\r'),
(16, 'Mikkel Grønhøj', 'Nielsen', 79, 'Italien ', 'Spring\r'),
(17, 'Oliver Østergaard', 'Hansen', 33, 'Kenya ', 'Spring\r'),
(18, 'Rune Solgaard', 'Larsen', 60, 'Peru ', 'Svømning\r'),
(19, 'Simon Johansen', 'Damm', 18, 'Canada ', 'Svømning\r'),
(20, 'Stine Abild', 'Mortensen', 274, 'Island ', 'Dans\r'),
(21, 'Thorstein Godske', 'Pedersen', 85, 'Argentina ', 'Spring\r'),
(22, 'Albert Lacuhr', 'Jacobsen', 119, 'Kina ', 'Fodbold\r'),
(23, 'Alberte Marie Knigge', 'Emgren', 215, 'Island ', 'Dans\r'),
(24, 'Alberte Skov', 'Valentin', 309, 'Indonesien ', 'Dans\r'),
(25, 'Alfred Andersen', 'Skræp', 99, 'Belgien ', 'Spring\r'),
(26, 'Allan', 'Colic', 16, 'Canada ', 'Svømning\r'),
(27, 'Amalie Biesbjerg', 'Jensen', 242, 'USA ', 'Fodbold\r'),
(28, 'Amalie Kofoed', 'Jacobsen', 237, 'USA ', 'Svømning\r'),
(29, 'Amalie', 'Pedersen', 287, 'Norge ', 'Svømning\r'),
(30, 'Amanda', 'Jørgensen', 249, 'Indien ', 'Fodbold\r'),
(31, 'Amelia Isilda', 'Nunes', 283, 'Egypten ', 'Fodbold\r'),
(32, 'Anders Dam', 'Frandsen', 28, 'Canada ', 'Svømning\r'),
(33, 'Anders Lund', 'Holgersen', 37, 'Brasilien ', 'Svømning\r'),
(34, 'Andreas', 'Hougaard', 39, 'Congo ', 'Svømning\r'),
(35, 'Andreas Hougaard', 'Hansen', 32, 'Brasilien ', 'Svømning\r'),
(36, 'Andreas Kildegaard', 'Jeppesen', 44, 'Peru ', 'Spring\r'),
(37, 'Anna Kathrine', 'Skjøth', 299, 'Polen ', 'Svømning\r'),
(38, 'Anna Runge', 'Larsen', 259, 'Mexico ', 'Dans\r'),
(39, 'Anna Sofie', 'Christensen', 318, 'Indien ', 'Spring\r'),
(40, 'Asger Schaumann Mundt', 'Andersen', 4, 'Congo ', 'Spring\r'),
(41, 'Asta Fonager', 'Aagaard', 320, 'Egypten ', 'Dans\r'),
(42, 'Astrid Skriver', 'Lorentzen', 262, 'Polen ', 'Dans\r'),
(43, 'Benjamin Jan', 'Danser', 115, 'Canada ', 'Spring\r'),
(44, 'Benjamin Mads', 'Andresen', 6, 'Congo ', 'Spring\r'),
(45, 'Camilla Lomborg', 'Vestergaard', 310, 'Indonesien ', 'Svømning\r'),
(46, 'Caroline Biesbjerg', 'Andersen', 203, 'Sverige ', 'Fodbold\r'),
(47, 'Caroline Krog', 'Jürgensen', 248, 'Chile ', 'Svømning\r'),
(48, 'Caroline', 'Mouret', 275, 'Egypten ', 'Fodbold\r'),
(49, 'Cecilie Frisesdahl Sand', 'Nikolaisen', 282, 'Egypten ', 'Spring\r'),
(50, 'Cecilie Gaarde', 'Hansen', 229, 'Mexico ', 'Svømning\r'),
(51, 'Cecilie Krogh', 'Pindstrup', 291, 'Egypten ', 'Spring\r'),
(52, 'Cecilie Mønsted', 'Mikkelsen', 272, 'Ungarn ', 'Fodbold\r'),
(53, 'Charlotte', 'Bisgaard', 206, 'Sverige ', 'Svømning\r'),
(54, 'Christian Aksel Lindemann', 'Stender', 116, 'Kina ', 'Svømning\r'),
(55, 'Christian Højvang', 'Jessen', 46, 'Holland ', 'Svømning\r'),
(56, 'Christine Maraea Schmidt Morth', 'Rasmussen', 295, 'Malaysia ', 'Svømning\r'),
(57, 'Christine Schack', 'Kock', 255, 'Polen ', 'Fodbold\r'),
(58, 'Clara Helene', 'Nunes', 284, 'Norge ', 'Fodbold\r'),
(59, 'Cæcilie Buchholt', 'Johansen', 247, 'Chile ', 'Svømning\r'),
(60, 'Daniel Holm', 'Johansen', 47, 'Belgien ', 'Svømning\r'),
(61, 'Emil', 'Dyremose', 24, 'Argentina ', 'Spring\r'),
(62, 'Emil Grønnegaard', 'Pedersen', 84, 'Kenya ', 'Spring\r'),
(63, 'Emil', 'Hedemann', 36, 'Argentina ', 'Fodbold\r'),
(64, 'Emil Lukas Kjærby', 'Hansen', 31, 'Peru ', 'Svømning\r'),
(65, 'Emma Bjørg Grosen', 'Hansen', 226, 'Mexico ', 'Spring\r'),
(66, 'Emma Desmareth', 'Johansen', 246, 'Chile ', 'Dans\r'),
(67, 'Emma Floutrup', 'Hansen', 224, 'Mexico ', 'Musik\r'),
(68, 'Emma Kjær', 'Pedersen', 285, 'Egypten ', 'Svømning\r'),
(69, 'Emma Kärkkäinen', 'Larsen', 260, 'Malaysia ', 'Dans\r'),
(70, 'Emma Lhjungmann', 'Hansen', 314, 'Indien ', 'Svømning\r'),
(71, 'Eva Bjerregård', 'Littau-Jensen', 261, 'Norge ', 'Dans\r'),
(72, 'Frederik Kjøller', 'Malmberg', 73, 'Italien ', 'Svømning\r'),
(73, 'Frederik Nicolai Ibsø', 'Agatz', 1, 'Congo ', 'Fodbold\r'),
(74, 'Frederik', 'Presskorn', 90, 'Holland ', 'Svømning\r'),
(75, 'Freja Elizabeth', 'Nicholas', 277, 'Egypten ', 'Svømning\r'),
(76, 'Freja', 'Jensen', 243, 'Chile ', 'Dans\r'),
(77, 'Freja Mørch', 'Sørensen', 305, 'Malaysia ', 'Dans\r'),
(78, 'Gorm Stege Vaaben', 'Rasmussen', 93, 'Holland ', 'Spring\r'),
(79, 'Gustav Anders', 'Schou', 117, 'Kina ', 'Fodbold\r'),
(80, 'Gustav Beck', 'Jørgensen', 49, 'Kina ', 'Svømning\r'),
(81, 'Gustav Meibom', 'Jørgensen', 50, 'Belgien ', 'Fodbold\r'),
(82, 'Christian Staalbo', 'Jørgensen', 48, 'Canada ', 'Spring\r'),
(83, 'Hans Christian Zareh', 'Lausten-Thomsen', 65, 'Spanien ', 'Svømning\r'),
(84, 'Helena Bak', 'Hollænder', 232, 'USA ', 'Musik\r'),
(85, 'Helene Deleuran', 'Christiansen', 210, 'USA ', 'Dans\r'),
(86, 'Ida Skytte', 'Holm', 233, 'USA ', 'Fodbold\r'),
(87, 'Jacob Nicklas', 'Poffler', 89, 'Thailand ', 'Spring\r'),
(88, 'Jacob', 'Rønn', 123, 'Canada ', 'Svømning\r'),
(89, 'Jacob Schilling Wulff', 'Petersen', 88, 'Japan ', 'Svømning\r'),
(90, 'Jakob', 'Larsen', 59, 'Holland ', 'Fodbold\r'),
(91, 'Jannick', 'Hagensen', 30, 'Belgien ', 'Svømning\r'),
(92, 'Jens Christian Birkholm', 'Ragner', 92, 'Japan ', 'Fodbold\r'),
(93, 'Jens Jakob Ellegaard', 'Petersen', 87, 'Japan ', 'Svømning\r'),
(94, 'Jens', 'Tinggaard', 105, 'Vietnam ', 'Spring\r'),
(95, 'Jeppe', 'Bredahl', 13, 'Argentina ', 'Spring\r'),
(96, 'Jeppe Snedker', 'Tamberg', 104, 'Italien ', 'Spring\r'),
(97, 'Joachim Fredeløkke', 'Rzempala', 96, 'Thailand ', 'Spring\r'),
(98, 'Joakim Lyhr', 'Larsen', 58, 'Holland ', 'Fodbold\r'),
(99, 'Johan Theis', 'Møller', 122, 'Kenya ', 'Svømning\r'),
(100, 'Johanna Tashdjian', 'Madsen', 265, 'Chile ', 'Musik\r'),
(101, 'Johanne Astrup', 'Christiansen', 209, 'Island ', 'Svømning\r'),
(102, 'Jonas Ejby Lentz', 'Svendsen', 100, 'Italien ', 'Svømning\r'),
(103, 'Jonas Holst', 'Due', 23, 'Peru ', 'Spring\r'),
(104, 'Jonas Hvid', 'Nordbo', 80, 'Vietnam ', 'Spring\r'),
(105, 'Jonas Kjærgaard', 'Larsen', 56, 'Japan ', 'Svømning\r'),
(106, 'Jonas Leth', 'Bjerg', 12, 'Canada ', 'Spring\r'),
(107, 'Jonas', 'Nyring', 81, 'Vietnam ', 'Fodbold\r'),
(108, 'Jonas Sandberg', 'Vilhelmsen', 109, 'Vietnam ', 'Svømning\r'),
(109, 'Josefine Holm', 'Sørensen', 302, 'Malaysia ', 'Svømning\r'),
(110, 'Josephine Kirstine Emborg', 'Mejer', 270, 'Ungarn ', 'Dans\r'),
(111, 'Jost Bech', 'Tøndering', 108, 'Japan ', 'Fodbold\r'),
(112, 'Julie Hildebrandt', 'Jensen', 241, 'Chile ', 'Dans\r'),
(113, 'Julie', 'Høegh-Jørgensen', 236, 'USA ', 'Svømning\r'),
(114, 'Kaisa Amalie Cock', 'Hansen', 228, 'Mexico ', 'Dans\r'),
(115, 'Kalle Engelsted', 'Due', 22, 'Argentina ', 'Musik\r'),
(116, 'Karoline Sofie Juul', 'Hansen', 319, 'Indien ', 'Spring\r'),
(117, 'Katrine Tetzschner', 'Madsen', 266, 'Ungarn ', 'Svømning\r'),
(118, 'Kiki Dahl', 'Rasmussen', 294, 'Island ', 'Fodbold\r'),
(119, 'Kim Jong Engsted', 'Lassen', 63, 'Spanien ', 'Spring\r'),
(120, 'Kirstine', 'Knold', 253, 'Chile ', 'Dans\r'),
(121, 'Kristian Bank', 'Lynggaard', 69, 'Spanien ', 'Fodbold\r'),
(122, 'Kristian Toft', 'Langæble', 55, 'Belgien ', 'Fodbold\r'),
(123, 'Lasse Hedemann', 'Hougaard', 38, 'Peru ', 'Fodbold\r'),
(124, 'Laura Kjøller', 'Bech', 204, 'Sverige ', 'Dans\r'),
(125, 'Lea', 'Mahato', 268, 'Ungarn ', 'Svømning\r'),
(126, 'Line', 'Holm', 234, 'Island ', 'Fodbold\r'),
(127, 'Line Kallesøe', 'Lyck', 263, 'Polen ', 'Spring\r'),
(128, 'Line Mia', 'Jensen', 245, 'Chile ', 'Svømning\r'),
(129, 'Linea Bruun', 'Jørgensen', 250, 'Chile ', 'Svømning\r'),
(130, 'Lior Edelberg', 'Shabat', 121, 'Kina ', 'Fodbold\r'),
(131, 'Liv Anemone Solbjerg', 'Persson', 288, 'Egypten ', 'Svømning\r'),
(132, 'Liv Schmidt', 'Petersen', 290, 'Egypten ', 'Dans\r'),
(133, 'Lotte Bunkenborg', 'Sørensen', 301, 'Malaysia ', 'Fodbold\r'),
(134, 'Louise Dybro', 'Nielsen', 278, 'Egypten ', 'Spring\r'),
(135, 'Louise', 'Jørgensen', 251, 'Chile ', 'Musik\r'),
(136, 'Lucas Demant', 'Augustinus', 7, 'Belgien ', 'Fodbold\r'),
(137, 'Lykke Nørgaard', 'Christoffersen', 212, 'Island ', 'Spring\r'),
(138, 'Lærke Sandholdt', 'Jensen', 244, 'Chile ', 'Spring\r'),
(139, 'Lærke Stræde Bladt', 'Toftgaard', 306, 'Indonesien ', 'Svømning\r'),
(140, 'Mads Juulsgaard', 'Sørensen', 103, 'Thailand ', 'Svømning\r'),
(141, 'Mads', 'Mathiesen', 74, 'Italien ', 'Spring\r'),
(142, 'Mads Victor', 'Nielsen', 78, 'Kina ', 'Svømning\r'),
(143, 'Magnus Bæk', 'Hartung', 34, 'Brasilien ', 'Fodbold\r'),
(144, 'Magnus', 'Quist', 91, 'Japan ', 'Spring\r'),
(145, 'Magnus', 'Rundstrøm', 95, 'Italien ', 'Svømning\r'),
(146, 'Maja Weinrich', 'Havlit', 231, 'Mexico ', 'Fodbold\r'),
(147, 'Malthe', 'Ahlstrøm', 2, 'Congo ', 'Fodbold\r'),
(148, 'Malthe Albrechtsen', 'Aaen', 112, 'Thailand ', 'Fodbold\r'),
(149, 'Marcus Kirkeløkke', 'Zenker', 114, 'Kina ', 'Fodbold\r'),
(150, 'Marcus Nyberg', 'Bech', 8, 'Vietnam ', 'Spring\r'),
(151, 'Marie Paludan', 'Wind', 312, 'Indien ', 'Dans\r'),
(152, 'Mark', 'Bøgelund', 118, 'Kina ', 'Spring\r'),
(153, 'Martha Juul', 'Kristensen', 256, 'Polen ', 'Spring\r'),
(154, 'Martin Slot Urup', 'Mikkelsen', 75, 'Italien ', 'Fodbold\r'),
(155, 'Martine Christiansen', 'Grave', 222, 'Mexico ', 'Fodbold\r'),
(156, 'Martine Josephine Sloth', 'Frederiksen', 316, 'Indien ', 'Dans\r'),
(157, 'Mathias Alkjærsig', 'Knudsen', 51, 'Brasilien ', 'Fodbold\r'),
(158, 'Mathias Dreyer', 'Lex', 66, 'Spanien ', 'Svømning\r'),
(159, 'Mathias Skjerbæk', 'Szast', 101, 'Japan ', 'Fodbold\r'),
(160, 'Mathilde', 'Bisbjerg', 205, 'Indonesien ', 'Fodbold\r'),
(161, 'Mathilde Brunhøj', 'Engstrøm', 216, 'Island ', 'Spring\r'),
(162, 'Mathilde Rafner', 'Kristiansen', 257, 'Polen ', 'Dans\r'),
(163, 'Matti Sander Nørskov', 'Andersen', 3, 'Congo ', 'Svømning\r'),
(164, 'Melissa Damsgaard', 'Sørensen', 304, 'Indonesien ', 'Spring\r'),
(165, 'Mette Amalie', 'Pedersen', 286, 'Norge ', 'Dans\r'),
(166, 'Mie Sofie Grønlund', 'Koch', 254, 'Ungarn ', 'Spring\r'),
(167, 'Mike Jens', 'Westergaard', 111, 'Vietnam ', 'Fodbold\r'),
(168, 'Mikkel Kaas', 'Rasmussen', 113, 'Kenya ', 'Fodbold\r'),
(169, 'Mikkel', 'Kønigsfeldt', 54, 'Holland ', 'Spring\r'),
(170, 'Mille Bader', 'Havkrog', 230, 'Mexico ', 'Dans\r'),
(171, 'Minna', 'Juul', 315, 'Polen ', 'Svømning\r'),
(172, 'Monique Vang', 'Damm', 214, 'Island ', 'Dans\r'),
(173, 'Morten Bastian', 'Madelung', 70, 'Spanien ', 'Spring\r'),
(174, 'Nanna Winther', 'Midtgaard', 271, 'Ungarn ', 'Fodbold\r'),
(175, 'Nicki', 'Jensen', 43, 'Peru ', 'Fodbold\r'),
(176, 'Nicolai', 'Larsen-Ledet', 62, 'Spanien ', 'Fodbold\r'),
(177, 'Nicoline', 'Fejer', 217, 'Island ', 'Musik\r'),
(178, 'Nicoline Trend', 'Ahrentsen', 201, 'Sverige ', 'Svømning\r'),
(179, 'Nikolai Vaabengaard', 'Olsen', 82, 'Kenya ', 'Svømning\r'),
(180, 'Nikolaj Arild', 'Madsen', 71, 'Vietnam ', 'Spring\r'),
(181, 'Nikoline Pors', 'Mathiesen', 269, 'Ungarn ', 'Svømning\r'),
(182, 'Nikoline Victoria', 'Hansen', 227, 'Polen ', 'Svømning\r'),
(183, 'Nina Skytte', 'Sørensen', 303, 'Indonesien ', 'Dans\r'),
(184, 'Noah Schak', 'Farlot', 26, 'Peru ', 'Musik\r'),
(185, 'Oliver Andreas Nørgaard', 'Bruun', 14, 'Canada ', 'Fodbold\r'),
(186, 'Peter Jøker', 'Trachsel', 106, 'Vietnam ', 'Musik\r'),
(187, 'Rasmus Holm', 'Jakobsen', 41, 'Brasilien ', 'Spring\r'),
(188, 'Rasmus Lollesgaard', 'Dencker-Jensen', 20, 'Brasilien ', 'Svømning\r'),
(189, 'Rasmus Sander', 'Berggreen', 9, 'Argentina ', 'Svømning\r'),
(190, 'Rikke', 'Flensburg', 219, 'Mexico ', 'Dans\r'),
(191, 'Rikke Uller', 'Hansen', 225, 'Mexico ', 'Dans\r'),
(192, 'Robert Hjemdal', 'Raahauge', 97, 'Thailand ', 'Svømning\r'),
(193, 'Sabine Storm', 'Nielsen', 280, 'Egypten ', 'Svømning\r'),
(194, 'Sander Schrøder', 'Dyvekær', 25, 'Argentina ', 'Svømning\r'),
(195, 'Sarah', 'Carlsson', 321, 'Indien ', 'Spring\r'),
(196, 'Sarah Juul', 'Christiansen', 211, 'Malaysia ', 'Dans\r'),
(197, 'Sebastian', 'Andersen', 5, 'Peru ', 'Spring\r'),
(198, 'Sebastian', 'Barnewitz', 120, 'Kina ', 'Svømning\r'),
(199, 'Sibel Hüttel Yavuz', 'Simonsen', 298, 'Indonesien ', 'Svømning\r'),
(200, 'Sif Amalie Lumbye', 'Floor', 317, 'Indonesien ', 'Svømning\r'),
(201, 'Signe  Lydersen Schjødt', 'Jensen', 238, 'USA ', 'Spring\r'),
(202, 'Signe Lei', 'Aagaard', 313, 'Indien ', 'Fodbold\r'),
(203, 'Simon', 'Jeppesen', 45, 'Belgien ', 'Fodbold\r'),
(204, 'Simon Stærk', 'Riber', 94, 'Thailand ', 'Spring\r'),
(205, 'Simone Kidholm', 'Boysen', 207, 'Island ', 'Dans\r'),
(206, 'Sofie', 'Alstrup', 202, 'Sverige ', 'Fodbold\r'),
(207, 'Sofie Salgård', 'Svinding', 322, 'Indien ', 'Spring\r'),
(208, 'Sofie Skovgaard Beck', 'Nielsen', 281, 'Norge ', 'Fodbold\r'),
(209, 'Sophie Maria', 'Poulsen', 292, 'Malaysia ', 'Fodbold\r'),
(210, 'Stine Bagger', 'Clausen', 213, 'Island ', 'Spring\r'),
(211, 'Søren Birch', 'Larsen', 57, 'Holland ', 'Svømning\r'),
(212, 'Teraza Balle', 'Ferguson', 218, 'Island ', 'Dans\r'),
(213, 'Theresa Bøg', 'Tolberg', 307, 'Indonesien ', 'Spring\r'),
(214, 'Therese Jetsmark', 'Geiker', 221, 'Mexico ', 'Svømning\r'),
(215, 'Thor Nilsson', 'Pedersen', 86, 'Kenya ', 'Svømning\r'),
(216, 'Tilde', 'Jensen', 239, 'USA ', 'Spring\r'),
(217, 'Tilde Sofia Cordes', 'Simonsen', 297, 'Malaysia ', 'Dans\r'),
(218, 'Tobias Vatnamo', 'Madsen', 72, 'Italien ', 'Spring\r'),
(219, 'Vi Vu Allan', 'Vo', 110, 'Vietnam ', 'Musik\r'),
(220, 'Victor Greve', 'Jensen', 42, 'Brasilien ', 'Fodbold\r'),
(221, 'Victor Hvid', 'Troelsen', 107, 'Vietnam ', 'Svømning\r'),
(222, 'Victoria Schmidt', 'Hansen', 223, 'Mexico ', 'Dans\r'),
(223, 'William Kjeldstrøm', 'Fischer', 27, 'Argentina ', 'Fodbold\r'),
(224, 'Zacharias Kuno', 'Søberg', 102, 'Thailand ', 'Spring\r');